name: pr-test
on: pull_request

env:
  DB_PASSWORD: root

jobs:
  pr-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Start Mysql Service
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE shoppingtest;' -uroot -proot

      - name: Set up JDK 21
        uses: actions/setup-java@main
        with:
          java-version: '21'
          cache: 'gradle'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.5

      - name: Run Test
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: wrapper
          arguments: test
          # gradle test -> admin, user모두
          # 멀티모듈 user, admin 모듈이 분리
          # arguments: user:test admin:test
